Add compile time option to disable floating point
laurencelundblade/QCBOR pull request #114
Opened 2021-07-08 13:27 UTC by matetothpal

This pull request adds the compile time option to disable floating point functionality in QCBOR (i.e. to conditionally compile floating point related code). Doing this compile time (in contrast to doing this linker time, as it is currently possible) can be necessary if the project using the QCBOR library has the requirements to use only general purpose registers only.

See GCC 6.31.2 AArch64 Function Attributes: 

> `general-regs-only`
> Indicates that no floating-point or Advanced SIMD registers should be used when generating code for this function. If the function explicitly uses floating-point code, then the compiler gives an error. This is the same behavior as that of the command-line option `-mgeneral-regs-only`.

The pull request also contains two other commits to add some extra builds to the CI to exercise the defines that make disabling/restricting floating point functionality of QCBOR.

2021-07-13 19:24 UTC, laurencelundblade commented
Still thinking, but a few comments. 

See https://github.com/laurencelundblade/qdv for the scripts I use to test and develop. I keep them separate to not impose the long build and test times on normal users. This fans out all combinations of ifdefs.

There is -DQCBOR_DISABLE_FLOAT_HW_USE, but it doesn't completely eliminate the use of the type double and float. When it is defined QCBOR will not do anything operation with a double or float other than return the type.

When I use GCC to compile with both -mgeneral-regs-only -DQCBOR_DISABLE_FLOAT_HW_USE I get errors, so probably your change is needed to be able to use -mgeneral-regs-only.

I need to check on what LLVM does.

Why would one set -mgeneral-regs-only? Presumably the compiler knows if the HW has floating point registers and will never generate code that uses them because it would be incorrect. On the other hand, if the HW has those registers and code is generated that uses them, but is never executed, what's the harm?

This is a fairly messy ifdef affecting interfaces and such. No other ifdef affects interfaces. I want to be sure this is really important.

2021-07-14 15:20 UTC, matetothpal commented
Thanks for looking at the PR. 

I didn't know about these scripts, They look really useful. I guess I'm OK to remove the CI related commits from this PR then, and use the scripts for testing myself.

if QCBOR needed to be used in supervisory software, typically the supervisory software disables usage of FPU due to memory foot print /latency complications. If the supervisory software needs to have FPU support enabled, then it makes the implementation complicated due to the way it manages the FPU context for user applications.

Using `-mgeneral-regs-only` gives the extra safety that the compiler refuses to generate code that uses FPU registers, compared to relying on the linker eliminating floating point related code. In addition to that if the linker is used for this purpose there is no way to detect if accidentally some FPU using code is referenced and hence not eliminated.

Indeed the change is quite messy. I also understand the concerns related to the ifdefs in the interface. One way to overcome this (not sure if it is possible at all) might be to organize floating point related functionality to separate c/h file. Again, not sure whether this could be done smoothly at all.

2021-07-14 17:23 UTC, laurencelundblade commented
Thank you for the work here.

Still thinking about this, but am coming to think the change is necessary.

I understand your comment about supervisor mode. It makes sense.

I also found this when trying to figure out what LLVM does in this regard. https://reviews.llvm.org/D40256

2021-07-17 03:48 UTC, laurencelundblade commented
So what happens if you give -mfloat-abi=soft?

This appears to work for both llvm and gcc.

It results in SW floating point being used in the ABI and for any actual calculation. If you use this with -DQCBOR_DISABLE_FLOAT_HW_USE it should result in QCBOR not using any floating point registers in any way and then be OK with the -mgeneral-regs-only flag.

With -DQCBOR_DISABLE_FLOAT_HW_USE QCBOR will still copy floating point numbers around, but it will never try to add, multiply or such with them. With the -mfloat-abi=soft that copying should always be in integer registers (except for AArch64 architectures).

I'm thinking to recommend -mfloat-abi=soft plus -DQCBOR_DISABLE_FLOAT_HW_USE QCBOR rather than the big set of ifdefs to eliminate all use of double, float...

https://wiki.segger.com/GCC_floating-point_options
https://wiki.debian.org/ArmHardFloatPort/VfpComparison
https://reviews.llvm.org/D40256

2021-07-23 14:18 UTC, tamasban commented
Thanks for the proposal!

We will investigate it. Currently, both of us (Mate&me) is on leave. We will come back with the results in a few weeks.

2021-07-27 19:01 UTC, laurencelundblade commented
Also, look at the new version of the README.md. It has lots more info on floating point, though it may not be the solution.

Generally, I think you would want to define QCBOR_DISABLE_FLOAT_HW_USE QCBOR  and QCBOR_DISABLE_PREFERRED_FLOAT for the TFM use case.

2021-08-03 12:54 UTC, matetothpal commented
Sorry for the long delay, and thanks for looking into this problem further.

The reason we can't use `-mfloat-abi=soft` is just as you mentioned above: that option is not available for AArch64 compilers. The reason is that there is no soft floating point ABI defined for that architecture. This means that the `+nofp` and `+nosimd` modifiers won't work either for the `-mcpu` and `-march` options. 

So to restrict the usage of FP registers on AArch64 the only option seems to be `-mgeneral-regs-only` option, which unfortunately also restrict the usage of FP in the source code.

2021-08-06 04:51 UTC, laurencelundblade commented
OK. Understood soft doesn't work for you. Got a few other things going on so it will take some time to get to this.

2021-08-10 01:10 UTC, laurencelundblade requested changes
It's a thorough PR. I have three little change requests. Thx!

2021-08-10 09:18 UTC, matetothpal reviewed
Thanks for looking at the change. I updated the PR with the requested changes. Also rebased it on top of the current master (This meant rephrasing a bit the addition in the README.md)

2021-09-02 10:01 UTC, tamasban commented
@laurencelundblade:  Just wondering whether could you take a look at the fixes?

2021-09-05 18:08 UTC, laurencelundblade approved these changes

2021-09-05 19:09 UTC, laurencelundblade requested changes
This is a big messy change. Appreciate your help working through this. I won't promise that this is the last change I'll request. 

There is an error precedence issue. I think it should probably be like this:

/* For most tests the variance for #ifdefs is just the error code. */
#ifdef QCBOR_DISABLE_FLOATING_POINT
#define FLOAT_ERR_CODE(x) QCBOR_ERR_FLOAT_DISABLED
#elif QCBOR_DISABLE_PREFERRED_FLOAT
#define FLOAT_ERR_CODE(x) QCBOR_ERR_HALF_PRECISION_DISABLED
#elif QCBOR_DISABLE_FLOAT_HW_USE
#define FLOAT_ERR_CODE(x) QCBOR_ERR_HW_FLOAT_DISABLED
#else
#define FLOAT_ERR_CODE(x) x
#endif

The disable all error should take precedence. 

The above set of macros can be used to make this work in the tests and maybe in the code too. That macro can eliminate most of the nested #ifdefs in the error code checking for floating point since the only variance is by error code. Since it is a macro is can work for structure initializers too. With this macro the code will be neater than before this change.

It also seems like there is some float still enabled in the tests even with QCBOR_DISABLE_FLOATING_POINT. That might not be OK or as expected for some. Not sure what to do about it yet.

2021-09-07 08:08 UTC, matetothpal commented on src/qcbor_err_to_str.c
> +#ifdef QCBOR_DISABLE_FLOATING_POINT
Done

2021-09-07 15:51 UTC, matetothpal reviewed
Thanks you for looking at the change again. I agree that it is quite messy, and I'm happy to adjust it until you feel that it is in a state that it is OK to be merged. 

Regarding the macro `FLOAT_ERR_CODE`, I found that it is not always the case that the error returned by the QCBOR API is following the precedence that is outlined by your code. 

For example there are code parts that are only guarded by `#ifndef QCBOR_DISABLE_PREFERRED_FLOAT` or `#ifndef QCBOR_DISABLE_FLOAT_HW_USE`, and they seem to return the error code that reflects the macro that guards that function. 

Also there are error types that indicate disabled floating point support, although don't directly refer to the disabled feature, like `QCBOR_ERR_FLOAT_DATE_DISABLED`.

So to keep the behavior of the API's unchanged, I needed to introduced a more diverse set of macros (see _inc/qcbor/qcbor_private.h_), and there are also places where are couldn't use them. 

Please have a look, and if I misunderstood how things should go, I'm still OK to apply the `FLOAT_ERR_CODE(x)` macro as you defined it.

2021-09-13 21:39 UTC, laurencelundblade commented
Hi

This has kind of precipitated a general review of the floating-point error handling for me, so it's taking some time.

So far, your PR looks good. The macros you came up with for the errors seem right. Thanks for that work.

In the long term, I want to simplify the testing some more, but I will do that myself. You've done enough. :-). I plan to merge this after a little more checking.

Thx

2021-09-17 17:31 UTC, merged